### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by DotSlashNatalie** [kyrofox/iceproject#1]
What license is this under? If you haven't chosen one - I recommend MIT.

**Comment by GrimTheReaper** [comment]
+1
Although I recommend [Apache](http://www.apache.org/licenses/).

**Comment by DotSlashNatalie** [comment]
I would be ok with that too - my only vote against would be GPL. LGPL maybe but I would have strong recommendations against GPL.

**Comment by GrimTheReaper** [comment]
@nadams810 You could always create a PR of adding a license. I just recomend Apache because it protects the project in a few more ways than MIT does.
